apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2021-10-17T23:57:38Z"
  name: ansible-jobs
  namespace: automation
  resourceVersion: "37508"
  uid: 81207331-4740-4b1a-9592-be63083973a7
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: "{{ image_name }}"
            imagePullPolicy: IfNotPresent
            name: ansible-job
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* */1 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2021-10-18T00:22:00Z"
